#path 1 story
def path_prime():
    print " "
    print "For generations, your clan, the Sentries of the Southern Village have safeguarded the Great Tree."
    print "People from all over the kingdom came to receive healing from the tree's sap."
    print "Tragedy has struck; raiders attacked the village, hoping to use the tree for themselves."
    print "The tree was scorched and deformed by flaming projectiles and torches."
    print "Numerous Sentries lost their lives, many of them your friends and loved ones."
    print "Since then, the Great Tree's healing properties have waned, and its sap turned bitter."
    print "All over the kingdom people grow sick with a new disease brought by the barbarians."
    print "The kingdom's medics and priests are unable to cure the disease, and need the Great Tree. "
    print "All attempts to heal the tree were in vain."
    print "The greatest mystics and most talented alchemists were powerless to remedy the damage."
    print "Legend tells of a healing water, hidden away in a forgotten temple in the northernmost portion of the kingdom."
    print "Only it can restore the tree to its former glory."
    print "You are a young prodigy among the Sentries."
    print "You have the respect and admiration of the village for your bravery, and come from a great line of warriors."
    print "The task has fallen to you!"
    print "the Sentries have also fallen victim to this great plague, and so you must make the trek north, and save your home!"

def path_prime_2():
    print " "
    print " "

    print "You are sitting in your room."
    print "It has been many months since the last raider attack."
    print "The leader of the Sentries called a meeting last week, and it was decided,"
    print "that you would undertake the great task, to seek out the lost Temple."
    print "You've donned your family Armor, said farewell to your friends, and must say goodbye to your mother."
    print "She calls to you, and you heed her call. You find her lying in bed, the sickness present in her face."

    print " "

    print "MOTHER: There you are my child. For centuries, our clan has safeguarded the Great Tree."
    print "We have ensured that pilgrims from across the realm may benefit from its healing properties."
    print "But I, and all the Sentries, have failed in our duty."
    print "Your training is complete. I see you've donned the Sentry's armor. It suits you."
    print "Now, you must choose your weapon."
    print "The wilds are fraught with dangers. Go over to the chest, at the end of my bed."
    print "Now, choose, my child. What shall safegaurd you, on your mission?"
    print " "
    print " "

def path_prime_3():
    print " "
    print "Your MOTHER takes a moment to take in the sight of you: a tear comes to her eye."
    print "Though she may not admit it, she fears she may not see you again."
    print " "
    print "Now, go my child. Fly fast and true, to the north."
    print "Your first challenge will be passing through the forest. Take care not to wander off the path."
    print "Dangerous creatures reside there. Some of them savage things. Others command the languge of men, and can bewitch you."
    print "I love you."
    print " "
def path_prime_4():
    print "You are on the road now, a few miles away from your village."
    print "The forest stretches before you like an ocean of green, ready to engulf the weak."
    print "You take one last look at home before you carry on, your weapon clutched tightly."
    print " "
    print " "
def path_prime_5():
    print "THE FOREST"
    print " "
    print "The light grows dim as you venture deeper into the dense forest."
    print "You hurdle over dead logs, pass over streams, and sneak past slumbering bears."
    print "As the darkness grows, you notice a clearing in the distance, bathed in light."
    print "However, it is off the beaten path your family has shown you before."


def path_1_a(): #this will print out path1 story
    print " "
    print "MOTHER: So, the blade. You always excelled in combat training. May it serve you well."
    print "It is called Frostbreaker. It's a little worn, but has protected our clan for generations."
def path_1_1():
    print " "
    print "MOTHER: Yes, your archery skills are unmatched. The dagger you hold belonged to your grandfather, the old rogue!"
    print "Ha, if only he could see you now."
    print "I see you like the stealth approach, eh? Take care not to let those sticky fingers get you into trouble!"
def path_1_2():
    print " "
    print "MOTHER: Yes, of course. Your mind has always been your strongest asset."
    print "That staff was taken from a powerful sorceror, and the tome was your grandmother's."
    print "Your grandfather stole it from the Arcane University for her. Ha! If they could see you now."
    print "Take care child, that you do not become drunk on the power of the arcane;"
    print "you are skilled, but you toy with powerful magics."
    print "Take care not to shout. A mage's voice is their greatest weapon."
def path_1_3():
    print " "
    print "MOTHER: My child, you must choose your weapon. Time is of the essence!"
def path_f_1():
    print " "
    print "You head off the beaten path, and get closer and closer to the light."
    print "The clearing is covered in grass and flowers, almost heavenly in appearance."
    print "As you step into the clearing, you see a small, winged creature, similar to a human."
    print "It is a fairy!"
def path_f_1_1():
    print "You approach the fairy cautiously. It looks up as you step forward, and lands on a flower."
    print "Suddenly, the other flowers begin to rustle, and a din erupts in the clearing."
    print "One hundred fairies appear in place of the flowers, and swarm towards you!"
    print "Ready your weapon!"
def path_f_1_2():
    print "You swing your sword wildly and raise your shield, battering fairies left and right."
    print "For every one you strike, five more attack you, scratching at your face, and trying to tear off your armor."
    print "You start to run, circling the clearing at your top speed, forcing the fairies to pursue."
    print "They act as bees might, a hive mind, condensing into a cloud of wings."
    print "Just as they begin to gain on you, you turn and raise your shield, stopping the creatures dead in their flight path."
    print "You sheathe your sword and continue on, bruised and exhausted, but alive."

def path_f_1_3():
    print "You recall your studies and cast a spell of inertia, stopping the angry creatures in their tracks."
    print "Their eyes and mouths still move, and the creatures chatter rabidly."
    print "You recognize their language, and are able to speak with them!"
    print "The chief fairy claims you have disturbed their rest, and must pay a toll to pass their field."
    print "You debate him thoroughly, finally agreeing to teach them the spell you cast on them."
    print "You release the creatures from their bondage, and they peacefully gather around for the lesson, as fairies are known for their magical prowess."
    print "As night begins to set in the fairies celebrate with you, sharing their libations and playing their music."
    print "You sleep heartily amidst them, but when you wake the next morning, they have disappeared."
    print "You return to your path, wondering whether the creatures had been there at all."
    print "When you check your armor, you find a bag filled with coins; perhaps a prize won from some unlucky traveler, who couldn't speak fairy."

def path_f_1_4():
    print "You dodge the initial attack, and drop a smokebomb of your own design."
    print "The creatures are blinded and some even drop from the smoke."
    print "Swiftly you slip back into the forest, leaping through the trees."
    print "The fairies are incensed, and head off in different directions, attempting to find you."
    print "You wait until nightfall, and witness the creatures going in and out of a small log, hidden from view, incessntly."
    print "One of them finally returns with a gold coin, which they pass around and laugh madly."
    print "After some time they fall asleep, and you seize the oppurtunity."
    print "You quickly sneak past the slumbering creatures, careful not to touch ground in the clearing."
    print "You reach the log and find a veritable treasure trove, loot captured from less skilled travelers."
    print "You qickly fill your pockets, careful not to overburden yourself."
    print "You slip away just as one of the creatures comes to check the log, and disappear as they frenzy."

def path_f_1_5():
    print "You continue on the path ahead, ever wary of danger."
    print "You venture further into the forest as the shadows grow, and eventually"
    print "consume the woods. You begin to hear the calls of savage bests,"
    print " the howls of wolves, and screeches of nocturnal birds on the hunt."
    print "Fear begins to set in; though you are brave, the tales you heard in youth torture your imagination."
    print "You begin to panic, and clamor through the dark, searching for shelter."
    print "You finally find it; a small cave, elevated from the forest floor, atop a cliff."
    print "You hoist your baggage and begin the climb, desperate to escape the cacophany of the forest."
    print "You finally reach the top, breathe a sigh of relief, and set up camp, just outside the cave, safe."
    print "Or so you think..."
    print " "
    print " "
    print "Your fire grows dim, and the night winds cut through your blankets,"
    print "But you endure, and finally fall asleep. Though it does not last."
    print "Soon after you have slipped into the grasp of Morpheus, you feel a soft rumble on the ground."
    print "It is coming from the cave, and grows ever larger."
    print " "
def path_f_1_6():
    print " "
    print "After your encounter with the fairies, your mother's message hits home."
    print "You must be on guard at all times in the forest."
    print " "
    print " "
    print "You venture further into the forest as the shadows grow, and eventually"
    print "consume the woods. You begin to hear the calls of savage bests,"
    print " the howls of wolves, and screeches of nocturnal birds on the hunt."
    print "Fear begins to set in; though you are brave, the tales you heard in youth torture your imagination."
    print "You begin to panic, and clamor through the dark, searching for shelter."
    print "You finally find it; a small cave, elevated from the forest floor, atop a cliff."
    print "You hoist your baggage and begin the climb, desperate to escape the cacophany of the forest."
    print "You finally reach the top, breathe a sigh of relief, and set up camp, just outside the cave, safe."
    print "Or so you think..."
    print " "
    print " "
    print "Your fire grows dim, and the night winds cut through your blankets,"
    print "But you endure, and finally fall asleep. Though it does not last."
    print "Soon after you have slipped into the grasp of Morpheus, you feel a soft rumble on the ground."
    print "It is coming from the cave, and grows ever larger."
    print " "

def path_f_2_1():
    print "You grab your shield and raise Frostbreaker, ready to face whatever beast or foul creature"
    print "may step forth from the cave. The ground shakes, and you fear the cliff may collapse itself!"
    print "Finally the beast steps into frame: a large wolf, the size of a horse! It's teeth are bared,"
    print "gleaming bright under the light of the moon. On instinct, you drop to a defensive stance,"
    print "ready to face the wolf. You are shocked beyond belief when the creature lets out a hearty laugh,"
    print "as if it were human itself."
def path_f_2_2():
    print "You flip through your spellbook and cast protection on yourself,"
    print "Then move onto the offensive spells; your specialty. You breathe deeply"
    print "and steady your mind, focusing so your spells come through clearly;"
    print "you have to mean them. The creature's footsteps grow louder, and you steel"
    print "yourself for battle. It finally steps through the mouth of the cave:"
    print "An enormous wolf! It's eyes gleam with vicious intent, reflecting the moonlight."
    print "You recall the spell of ice and ready it, but your concentration is broken by"
    print "the creature's voice, low and terrible:"
    print "WOLF: Ha! What's this? A human wielding magic? It has been some time since"
    print "I have encountered one of your species, some time indeed."
def path_f_2_3():
    print "You see a small ridge above the entrance to the cave, and work your way up there"
    print "as the creature's footsteps get louder. You reach the ridge and ready your bow,"
    print "ready to loose an arrow into whatever creature may appear; and what appears sends"
    print "a shudder down your spine: A wolf the size of two horses! Its massive frame can barely"
    print "fit past the cave entrance. You're unsure if your arrow can even pierce the hid of such a being."
    print "More shocking, the creature speaks, its voice echoing through the trees."
    print " "
    print "WOLF: Hmmm, what is this I smell; something I haven't smelled in a long, long time..."
    print " "
    print "The wolf breathes deeply through its long snout, the air it breathes visible."
    print " "
    print "WOLF:Ah, yes, that's it. Human."

def path_f_2_4():
    print "Terror fills your body as you stare into the eyes of the creature."
    print "It licks its chops and stares through to your soul."
    print "To your surprise, despite having your weapon raised,"
    print "it sits, looking at you with as much curiosity as rabid hunger."
    print " "

def path_f_2_5():
    print "You draw your bow back and aim for the creature's head."
    print "Sweat covers your hands, and you slip, a rare mistake."
    print "You hit the creature in its shoulder, but it bounces right off."
    print " "
    print "WOLF: Oh, come now. You're better than sneaking about in the dark,"
    print "my human friend. Your species' weaponry is as useless as it's always been."
    print "Come out, and we can have, a friendly discussion."
    print " "

def path_f_2_6():
    print " "
    print "You decide to face the creature, and jump down."
    print "Terror fills your body as you stare into the eyes of the creature."
    print "It licks its chops and stares through to your soul."
    print "To your surprise, despite having your weapon raised,"
    print "it sits, looking at you with as much curiosity as rabid hunger. "
    print " "
    print " "
